version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  frontend: # name of the first service
    build: ./frontend # specify the directory of the Dockerfile
    image: frontend_react:frontend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4200:3000 # specify port forewarding

  database: # name of the third service
    build: ./database
    image: database_mysql:database
    environment:
      - MYSQL_DATABASE=React
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "4306:3306"

  backend: #name of the second service
    build: ./backend # specify the directory of the Dockerfile
    image: backend_express:backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database

  jenkins:
    image: jenkins:2.6
    restart: "always"
    volumes:
      - jenkins:/var/jenkins_home
    ports:
      - "50000:8080"  